---

#DHCP Exlusion range
dhcp_excluded_start1: "192.168.99.1"
dhcp_excluded_end1: "192.168.99.10"
dhcp_excluded_start2: "192.168.10.128"
dhcp_excluded_end2: "192.168.10.254"
dhcp_excluded_start3: "192.168.10.1"
dhcp_excluded_end3: "192.168.10.127"

# VLAN 99 Configuration
vlan99_network: "192.168.99.0"
vlan99_mask: "255.255.255.0"
vlan99_default_router: "192.168.99.1"

# VLAN 10 Configuration
vlan10_network: "192.168.10.0"
vlan10_mask: "255.255.255.0"
vlan10_default_router: "192.168.10.1"

# HSRP Configuration for VLAN 10 on Router-North1_1
hsrp_interface_10: "GigabitEthernet0/1.10"
hsrp_virtual_ip_10: "192.168.10.1"
hsrp_priority_10: 110
hsrp_group_10: 10

# HSRP Configuration for VLAN 99 on Router-North1_2
hsrp_interface_99: "GigabitEthernet0/0.99"
hsrp_virtual_ip_99: "192.168.99.1"
hsrp_priority_99: 110
hsrp_group_99: 99

# HSRP Configuration for VLAN 98 on Router-North1_3
hsrp_interface_98: "GigabitEthernet0/1.98"
hsrp_virtual_ip_98: "192.168.98.1"
hsrp_priority_98: 110
hsrp_group_98: 98

# HSRP Configuration for Router-North2_1
hsrp_interface2_99: "GigabitEthernet0/0.99"
hsrp_virtual_ip2_99: "192.168.99.1"
hsrp_priority2_99: 100
hsrp_group2_99: 99  # Standby group number

# HSRP Configuration for Router-North2_2
hsrp_interface2_10: "GigabitEthernet0/1.10"
hsrp_virtual_ip2_10: "192.168.10.1"
hsrp_priority2_10: 100
hsrp_group2_10: 10  # Standby group number

# HSRP Configuration for Router-North2_3 
hsrp_interface2_98: "GigabitEthernet0/1.98"
hsrp_virtual_ip2_98: "192.168.98.1"
hsrp_priority2_98: 100
hsrp_group2_98: 98


# EtherChannel Configuration
etherchannel_group: 1
etherchannel_mode: "active"
etherchannel_interface1: "GigabitEthernet0/1"
etherchannel_interface2: "GigabitEthernet0/2"

# EtherChannel Configuration
etherchannel_group: 1
etherchannel_mode: "active"  # Options: active, passive, on
etherchannel_interface1: "GigabitEthernet0/1"
etherchannel_interface2: "GigabitEthernet0/2"
allowed_vlans: "10,20,99,98"
